== Detailed information

=== Labels

Labels either end with ':' or have to start at the first column.

A label starting with a dot ('.') is a _local_ label and treated
as _lastLabel.label_, where _lastLabel_ is the closest previous
_non local_ label.

A label can be also called '$'.

Referencing '+' will mean the closest _following_ '$' label.
Referencing '-' will mean the closest _previous_ '$' label.

Repeated '-' or '+' signs means to skip further.


=== Symbol lookup

A function call is first looked up among internal functions, then any
functions defined in LUA.

Opcodes that are not recognized are also tried as a macro, if one exists.


=== AST Cache

The parser works by first creating an AST (tree representation) of the
source, and then using this representation to do all work.

AST:s are cached on disk, so the second time you assemble a file that
has not been changed, assembling will be much faster.

AST:s are saved in `$HOME/.basscache`


=== Basic Operation in Detail

The source is parsed top to bottom.Included files are inserted
at the point of inclusion.

Symbols are defined through labels, symbol assignments or indirectly
through meta commands such as "!section" or "!test".

If an expression references an undefined symbol, it is assumed to
be zero and flagged as "undefined".

If an existing symbol gets assigned a new value, it is also flagged
as "undefined", since we need to make another pass to make sure all
it's previous references are resolved to the correct value.
This happens when code size changes, as subsequent labels are moved
to new locations.

When all source code is parsed, the undefined list is checked;

* If it is empty we are done.
* If all entries now also exist in the symbol table, we clear
the undefined list and make another pass.
* Otherwise we have an error, and report the undefined symbols.

A _branch_ instruction to an undefined or incorrect label may
temporarily be too long. This error must be postponed until all
parsing is done.

Macros use normal symbols as arguments. These symbols are only set
during macro evaluation. If a macro argument "shadows" a global
symbol a warning is issued.

Macros affect the symbol table, so you can set symbols from macros.
If you don't want to pollute the symbol table, used "."-symbols, they
will be local to the macro.

The symbol table supports the following types:

* Number (`double`)
* String (`std::string_view`)
* Byte Array (`std::vector<uint8_t>`)
* Number Array (`std::vector<double>`)

