
== Features

=== Unit Tests

You can pop a `!test` line in front of any subroutine,
and it will be executed in the bass emulator as part of
the build process.

You can also use `!check` to verify register contents,
or even execute lua code during the test run.

This won't affect code generation.


[source,ca65]
----
    !test A=3,X=4,Y=5
add_axy:
    clc
    stx $02
    !run {: print_fmt("{:x}", mem_read(2)) :}
    adc $02
    sty $02
    adc $02
    !check A == 12
    rts
----


=== Functional programming

Bass uses the traditional support in assemblers to allow you
to evaluate expresssions wherever constants are used and takes
it further.

You can think of it like a bass specific language that can
be used whenever expressions can be evaluated.

There are also no special types of variables, everything is
stored in the symbol table.

Symbols can take on non-numeric values, such as arrays, strings, lambdas and maps, and there are functions that can operate on and transform these values.

A lot of logic can therefore be performed directly in assembly
using functions.

[source,ca65]
----
load_adress = be_word(load("some.prg")[0:2])

!rept 100 { label[my_fun(i)]:
              lda #(i + other_fn(i))
              !fill some_array[i*10:i*10+10]
           }
----

=== Indexed Labels

Labels can be indexed. This is convenient for creating repeated
labels inside macros or rept statements.

[source,ca65]
----
    !rept 5 {
vec[i]:
        lda #0
        jmp jump_start + i * 3
}
    jsr vec[3]
----

=== Arrays and slices

Symbols can refer to arrays in addition to numbers. Arrays can
be sliced. Array literals can be used directly.

Note that there is a difference between an array of bytes and an
array of numbers.

[source,ca65]
----
some_bytes = bytes(9,8,7,6,5)
!assert some_bytes[3:2] == bytes(6,5)

a_list = [3.14, 9999, $5000]
!rept a_list { !print v }

data = load("some.prg")
load_address = be_word(data[0:2])
----

=== Lua

Lua is fully integrated in the assembler. Lua code can be used to
generate data, or even be called from 6502 code during testing.


=== $-variable

If a function result is not assigned to a return value, it is
automatically placed in the special variable `$`. It makes it
easier to chain expressions without using temporary variables.

[source,ca65]
----
    load_png("../data/face.png")
    layout_image($, 8, 8)
    image = index_tiles($.pixels, 8*8)
----


=== Lambdas

A lambda is also a value. This can be used to fill memory.

[source,ca65]
----
my_sin = [x -> sin(x) * 255 ]

sine0:
    !fill 256, my_sin
----
