
== The Bass 6502 Assembler

* ACME like syntax
* Aims to be on par with Kickassembler in automation/scriptability,
but with less complexity
* Unit tests through internal emulator
* Open and easily extendable source

See this http://apone.org/bass/part1.html[TUTORIAL] for a tutorial / introduction.

=== Normal operation

Run `bass <source_file>` to assemble and produce `result.prg`, which will
be a standard C64 executable (first 2 bytes are run address).

`bass -f raw -i myfile.asm -o myfile.bin`

Will assemble myfile.asm to myfile.bin without the 2-byte header.

`bass -DSKIP_INTRO=1 -x sid.lua music.asm`

Will set SKIP_INTRO=1 and load the specified _lua_ file before assembling.

=== Running programs

To run an assembly program in the internal emulator (see PET100.adoc)
use the `--run` option. This will assemble the given file and load all
it's section into the emulators memory. It will also watch the file
for changes, and re-assemble and restart on change.

=== Example source

[source,ca65]
----
    VRAM_LO = $9f00
    VRAM_HI = $9f01
    !macro SetVRAM(a) {
        .lo = <a;
        .hi = >a;
        lda #.lo
        sta VRAM_LO
        !if .lo != .hi { lda #.hi }
        sta VRAM_HI
    }

    !section "main", $1000
start:

    ; Clear 1K
    ldx #0
$   !rept 4 { sta $1000+i*256,x }
    dex
    bne -

    SetVRAM(0x1234)
    ldx #end - text
$   lda start,x
    sta $1000,x
    dex
    bne -
    rts

text:
    !byte "Text to copy", 0
end:
    
    ; --- Generate sine table with and without LUA

    !define mysin(x, amp, size) {
        (sin(x * Math.Pi * 2 / size) * 0.5 + 0.5) * amp
    }
sin:
    !fill 100 { mysin(i, 255, 100) } 

%{ -- LUA code
function make_sin(amp, size)
    res = {}
    for i=0,size-1,1 do
        res[i+1] = (math.sin(i * math.pi * 2/ size) * 0.5 + 0.5) * amp
    end
    return res
end
}%

sin2:
    !fill make_sin(255, 100)

    !assert make_sin(5, 5)[1] == round(mysin(1, 5,5))
    !assert make_sin(5, 5)[3] == round(mysin(3, 5,5))
----

See http://apone.org/bass/example.asm.html[example.asm] for a full example.
