== Meta Reference

All meta commands take the same basic form; An exclamation mark followed by an identifier, then an optional set of arguments, followed by zero, one or two
blocks enclosed in curly braces.


=== !section

1. `!section <name>, <start> [,<options>] [ { <statements...> } ]`
2. `!section <name>, in=<parent> [,<options>] [ { <statements...> } ]`

Create a section. All code and data must be placed into a section.
The sections are gathered at the end and written to the output file.

If a block is given, it specifies the entire section contents, and the previous section will be restored after.

If no block is given, this section is active until the next section directive.

A _root_ section is a a top level section with no parent. It must have a start address.

A _leaf_ section is a section without children.
Only leaf sections may contain data.

* _name_ : Name of the section. Not required for child sections.
* _start_ : Start in memory. Only required for root sections.
* _size_ : Fixed size of section. Normally given for root sections.
* _in_ : Parent of section. Makes this section a child section.
* _pc_ : Set the initial program counter. Defaults to _start_.

* _align_ : Set alignment (in bytes) of this section
* _file_ : Set output file of this section. Will remove the section from the main output file.
* _bank_size_ : Makes this section a banked section with given bank size.
Child sections can not overlap bank boundary.

* _ReadOnly_ : Flag that marks this section (and all children) as read only. Used for ROM areas.

* _NoStore_ : Flag that marks this section as not
having data in the output file. This is normally used for the zero page, and other bss sections.

Unrecognized options will be passed on to the output module.

1. Create a root section beginning at address _start_. If a block is provided, all statements goes into the section, otherwise the section is active until the next section directive.
2. Create a child section.

==== Example
[source,ca65]
----
    !section "RAM", $0000
    !section "main", in="RAM", start=$801
    !section "data", in="RAM"

    !section "code", in="main"
    !byte $0b,$08,$01,$00,$9e,str(start),$00,$00,$00
start:
----

=== !rept

1. `!rept [<ivar>=]<count> { <statements...> }`
2. `!rept <array> { <statements...> }`

Repeat a block of statements a specific number of times.

1. Evaluate _statements_ _count_ times.For each iteration, set the symbol <ivar> to the iteration number.If <ivar> is not provided, it defaults to `i`.

2. Parse statements once for each item in _array_.For each iteration, sets `i` to the iteration number and `v` to the `i`th  value in the array.

==== Example
[source,ca65]
----
    !rept 25 { nop }
xor_data:
    secret = [0x35, 0xcf, 0xa9, 0x44]
    !rept load("raw.dat") {
        !byte secret[i % len(secret] ^ v
    }
----
=== !fill

1. `!fill <array>`
2. `!fill <count> [, <value>]`
3. `!fill <count>, <lambda>`

Put data into memory, Essentially a shorthand for
`!rept <arg> { !byte <expression }`.

1. Put array in memory.
2. Fill memory with contant value, default is zero.
3. Call lambda with values 0 through count-1 and put result in memory

==== Example
[source,ca65]
----
    !fill 256
    !fill load("data. bin")
    !fill 10, [ i -> sin(i * Math. Pi / 5 ]
----

=== !macro

1. `!macro <name>(<args>...) { <statements...> }`

Create a macro. A macro can be called at a later time, at which point its
contents will be inserted into the assembly for parsing.

1. Create a macro that will insert `<statements>`.

=== !byte

1. `!byte <expression> [,<expression>]...`

Insert bytes into memory.

=== !word

1. `!word <expression> [,<expression>]...`

Insert 16bit words into memory.

=== !byte3

1. `!byte3 <expression> [,<expression>]...`

Insert 24bit words into memory. Useful for C64 sprites.

=== !text

`!text <string> [,<string>]`

Insert characters into memory.Characters are translated using
current translation table.

=== !chartrans

1. `!chartrans <string>, <c0>, <c1>... [<string>, <c0>, <c1>...]`
2. `!chartrans`

Setup the translation of characters coming from `!text` commands.

1. Each character from the provided _string_ should be translated to each
subsequent number, in order.The number of values should be equal to the
number of characters in the string.
2. Reset tranlation to default.

=== !assert

* `!assert <expression> [,<string>]`

Assert that _expression_ is true.Fail compilation otherwise.
Asserts are only evaluated in the final pass.

=== !align

* `!align <bytes>`

Align the _Program Counter_ so it is evenly dividable with _bytes_.
Normal use case is `!align 256` to ensure page boundary.

===  `!pc`

* `!pc <address>`

Explicitly set the _Program Counter_ to the given address.

=== !ds

* `!ds <bytes>`

Declare an empty sequence of _size_ bytes.Only increase the _Program Counter_, will not put any data into the current section.


=== !enum

`!enum [<name>] { <assignments...> }`

Perform all assignments in the block.If _name_ is given,
assignments are prefixed with `name.`.

Assignments must take the form `symbol = <number>` or just `symbol`, and must be placed on separate lines.

=== !if

1. `!if <expression> { <statements...> } [ else { <statements...>} ]`
2. `!ifdef <symbol> { <statements...> } [ else { <statements...>} ]`
3. `!ifndef <symbol> { <statements...> } [ else { <statements...>} ]`
4. `!elseif <symbol> { <statements...> }`
5. `!else <symbol> { <statements...> }`

Conditional parsing of statements.

=== !include

* `!include <filename>`

Include another file, relative to this file.

=== !incbin

* `!incbin <filename>`

Include a binary file, relative to this file.

=== !script

* `!script <filename>`

Include a script file, relative to this file.

=== !cpu

* `!cpu <cpuname>`

Set the CPU to use.Valid arguments are only `"6502"` or `"65c02"`.

=== !test

* `!test [<name>] [<registers>]`

Mark the current position (PC) as the start of a test.
Registers take the form: <reg>=<value>, ...

* `!test [<name>] <address> [<registers>]`

Create a test that starts at _address_.

=== !log

* `!log <text>`

Runtime log function during tests.Registers are available as special
arguments between braces ({A}, {X}, {Y} etc).

==== Example
[source,ca65]
----
    !test
    tax
    !log "We are here, X={X}"
----

=== !check

* `!check <expression>`

This is similar to assert, except it happens _runtime_ during the
execution of tests.Symbols A,X,Y,SP,SR are available in expressions.

==== Example
[source,ca65]
----
    !test
    lda #2
    sec
    rol a
    !check A == 5
----

=== !run

* `!run {: <lua code> :}`

Run lua code during tests.This can be used for more advanced checks and
logging.
